Repository 3PillarGlobal-Czechia/interview-app-api, pull requests merged in 2022-03, with the labels that each got.

#39 Add LICENSE file
  LICENSE
Labels: documentation

#41 Update README.md
  README.md
Labels: documentation

#53 change use case input objects to readonly structs
  src/WebApi/Application/UseCases/Question/CreateInterviewQuestion/CreateInterviewQuestionInput.cs
  src/WebApi/Application/UseCases/Question/CreateInterviewQuestion/CreateInterviewQuestionUseCase.cs
  src/WebApi/Application/UseCases/Question/GetInterviewQuestion/GetInterviewQuestionInput.cs
  src/WebApi/Application/UseCases/Question/GetInterviewQuestion/GetInterviewQuestionUseCase.cs
  src/WebApi/Application/UseCases/Question/UpdateInterviewQuestion/UpdateInterviewQuestionInput.cs
  src/WebApi/Application/UseCases/Question/UpdateInterviewQuestion/UpdateInterviewQuestionUseCase.cs
  src/WebApi/Application/UseCases/QuestionSet/CreateQuestionSet/CreateQuestionSetInput.cs
  src/WebApi/Application/UseCases/QuestionSet/CreateQuestionSet/CreateQuestionSetUseCase.cs
  src/WebApi/Application/UseCases/QuestionSet/GetQuestionSet/GetQuestionSetInput.cs
  src/WebApi/Application/UseCases/QuestionSet/GetQuestionSet/GetQuestionSetUseCase.cs
  src/WebApi/Application/UseCases/QuestionSet/GetQuestionSets/GetQuestionSetsInput.cs
  src/WebApi/Application/UseCases/QuestionSet/GetQuestionSets/GetQuestionSetsUseCase.cs
  src/WebApi/Application/UseCases/QuestionSet/UpdateQuestionSet/UpdateQuestionSetInput.cs
  src/WebApi/Application/UseCases/QuestionSet/UpdateQuestionSet/UpdateQuestionSetUseCase.cs
  src/WebApi/UnitTests/Tests/Application/UseCase/QuestionSetTests/CreateQuestionSetUseCaseTest.cs
  src/WebApi/UnitTests/Tests/Application/UseCase/QuestionSetTests/GetQuestionSetUseCaseTest.cs
  src/WebApi/UnitTests/Tests/Application/UseCase/QuestionSetTests/GetQuestionSetsUseCaseTests.cs
  src/WebApi/UnitTests/Tests/Application/UseCase/QuestionSetTests/UpdateQuestionSetUseCaseTest.cs
  src/WebApi/UnitTests/Tests/Application/UseCase/QuestionTests/CreateQuestionUseCaseTest.cs
  src/WebApi/UnitTests/Tests/Application/UseCase/QuestionTests/GetQuestionUseCaseTest.cs
  src/WebApi/UnitTests/Tests/Application/UseCase/QuestionTests/UpdateQuestionUseCaseTest.cs
Labels: technical debt

#52 Add basic e2e tests using in memory database
  src/WebApi/End2endTests/E2ETestsBase.cs
  src/WebApi/End2endTests/End2EndTests.csproj
  src/WebApi/End2endTests/HttpHelpers.cs
  src/WebApi/End2endTests/HttpWrapper.cs
  src/WebApi/End2endTests/MyWebApplicationFactory.cs
  src/WebApi/End2endTests/QuestionSetTests/CreateQuestionSetTests.cs
  src/WebApi/End2endTests/QuestionSetTests/GetQuestionSetTests.cs
  src/WebApi/End2endTests/QuestionSetTests/GetQuestionSetsTest.cs
  src/WebApi/End2endTests/QuestionSetTests/UpdateQuestionSetTests.cs
  src/WebApi/End2endTests/QuestionTests/CreateQuestionTests.cs
  src/WebApi/End2endTests/QuestionTests/GetQuestionTests.cs
  src/WebApi/End2endTests/QuestionTests/UpdateQuestionTests.cs
  src/WebApi/End2endTests/StandardResponse.cs
  src/WebApi/End2endTests/Tests/GetUserTests.cs
  src/WebApi/Infrastructure/Repositories/QuestionListRepository.cs
Labels: feature

#68 add order to questions in a set
  src/WebApi/Application/Repositories/IQuestionSetRepository.cs
  src/WebApi/Application/UseCases/QuestionSet/CreateQuestionSet/CreateQuestionSetUseCase.cs
  src/WebApi/Application/UseCases/QuestionSet/UpdateQuestionSet/UpdateQuestionSetUseCase.cs
  src/WebApi/Infrastructure/Entities/InterviewQuestion.cs
  src/WebApi/Infrastructure/Entities/QuestionList.cs
  src/WebApi/Infrastructure/Entities/QuestionListInterviewQuestion.cs
  src/WebApi/Infrastructure/Migrations/20220328075959_AddOrderToQuestions.Designer.cs
  src/WebApi/Infrastructure/Migrations/20220328075959_AddOrderToQuestions.cs
  src/WebApi/Infrastructure/Migrations/MyDbContextModelSnapshot.cs
  src/WebApi/Infrastructure/MyDbContext.cs
  src/WebApi/Infrastructure/Repositories/GenericRepository.cs
  src/WebApi/Infrastructure/Repositories/InterviewQuestionRepository.cs
  src/WebApi/Infrastructure/Repositories/QuestionListRepository.cs
  src/WebApi/UnitTests/Tests/Application/UseCase/QuestionSetTests/CreateQuestionSetUseCaseTest.cs
  src/WebApi/UnitTests/Tests/Application/UseCase/QuestionSetTests/UpdateQuestionSetUseCaseTest.cs
Labels: enhancement

#70 change cors to allow any origin on dev environment
  src/WebApi/WebApi/Modules/CorsExtensions.cs
  src/WebApi/WebApi/Startup.cs
  src/WebApi/WebApi/appsettings.json
Labels: bug
